### ISSUE TITLE
adding new testdata

### ISSUE THREAD

**Issue by cehbrecht** [roocs/mini-esgf-data#3]
The new inventory (01.03.) does not have the following dataset anymore:
```
c3s-cmip6.CMIP.IPSL.IPSL-CM6A-LR.historical.r1i1p1f1.Amon.rlds.gr.v20180803
```

It was used in several rook tests:
https://github.com/roocs/rook/pull/127

We could replace it by the following dataset:
```
c3s-cmip6.CMIP.INM.INM-CM5-0.historical.r1i1p1f1.Amon.rlds.gr1.v20190610
```

There are also some other live tests using:
```
c3s-cmip6.ScenarioMIP.INM.INM-CM5-0.ssp245.r1i1p1f1.Amon.rlds.gr1.v20190619
``` 

Both or one of them need to be added to the mini-esgf testdata.

**Comment by cehbrecht** [comment]
@ellesmith88 would you like to add these datasets? :smile:

**Comment by ellesmith88** [comment]
@cehbrecht Yes I'll add these today 👍

**Comment by ellesmith88** [comment]
@cehbrecht done!
